const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Function,
		C3.Behaviors.Flash,
		C3.Plugins.AJAX,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.video.Acts.SetSource,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite2: 0},
	{oynaBtn: 0},
	{Mouse: 0},
	{meblogo: 0},
	{oyunnasilBtn: 0},
	{Touch: 0},
	{Audio: 0},
	{Sprite: 0},
	{gitBtn: 0},
	{anasayfaBtn: 0},
	{Video: 0},
	{Sprite3: 0},
	{Video2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Pin: 0},
	{kutleler: 0},
	{listeler: 0},
	{meyve_sebzeler: 0},
	{terazi_konsol: 0},
	{solkefe: 0},
	{Solid: 0},
	{sagkefe: 0},
	{Function: 0},
	{ekle: 0},
	{cikar: 0},
	{esit: 0},
	{aktif: 0},
	{Flash: 0},
	{yeniListe: 0},
	{erzakal: 0},
	{Sprite6: 0},
	{Video3: 0},
	{AJAX: 0},
	{Sprite7: 0},
	{erzakyonerge: 0},
	{alisBitirBtn: 0},
	{erzakListe: 0},
	{Sprite8: 0},
	{Video4: 0},
	{erzaklar: 0},
	{seffafkap: 0},
	{kaptakierzak: 0},
	{sesBtn: 0},
	{kurek: 0},
	{kutleTxt: 0},
	{tik: 0},
	{yerlesti: 0},
	{Platform: 0},
	{kutle: 0},
	{tamamButon: 0},
	{Browser: 0},
	{bilgiBtn: 0},
	{tamekranBtn: 0},
	{bilgibutonlari: 0},
	{sayfalar: 0},
	{syfKapatBtn: 0},
	{Devam: 0},
	{Sprite9: 0},
	{Yazı: 0},
	{butonlar: 0},
	{sesacik: 0},
	{frameno: 0},
	{dolumframe: 0},
	{a: 0},
	{framesayisi: 0},
	{solkutle: 0},
	{kutleframe: 0},
	{listedekikutleler: 0},
	{asama: 0},
	{altasama: 0},
	{salinim: 0},
	{frame_number: 0},
	{msY: 0},
	{msX: 0},
	{tikY: 0},
	{tikX: 0},
	{oyunaktif: 0},
	{cikarTik: 0},
	{ekleTik: 0},
	{erzakY: 0},
	{tamambutonu: 0},
	{erzakX: 0},
	{erzakkutleler: 0},
	{git: 0},
	{lms: 0}
];

self.InstanceType = {
	Sprite2: class extends self.ISpriteInstance {},
	oynaBtn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	meblogo: class extends self.ISpriteInstance {},
	oyunnasilBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	gitBtn: class extends self.ISpriteInstance {},
	anasayfaBtn: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	kutleler: class extends self.ISpriteInstance {},
	listeler: class extends self.ISpriteInstance {},
	meyve_sebzeler: class extends self.ISpriteInstance {},
	terazi_konsol: class extends self.ISpriteInstance {},
	solkefe: class extends self.ISpriteInstance {},
	sagkefe: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	ekle: class extends self.ISpriteInstance {},
	cikar: class extends self.ISpriteInstance {},
	esit: class extends self.ISpriteInstance {},
	yeniListe: class extends self.ISpriteInstance {},
	erzakal: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Video3: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	erzakyonerge: class extends self.ISpriteInstance {},
	alisBitirBtn: class extends self.ISpriteInstance {},
	erzakListe: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Video4: class extends self.IWorldInstance {},
	erzaklar: class extends self.ISpriteInstance {},
	seffafkap: class extends self.ISpriteInstance {},
	kaptakierzak: class extends self.ISpriteInstance {},
	sesBtn: class extends self.ISpriteInstance {},
	kurek: class extends self.ISpriteInstance {},
	kutleTxt: class extends self.ITextInstance {},
	tik: class extends self.ISpriteInstance {},
	kutle: class extends self.ISpriteInstance {},
	tamamButon: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bilgiBtn: class extends self.ISpriteInstance {},
	tamekranBtn: class extends self.ISpriteInstance {},
	bilgibutonlari: class extends self.ISpriteInstance {},
	sayfalar: class extends self.ISpriteInstance {},
	syfKapatBtn: class extends self.ISpriteInstance {},
	Devam: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Yazı: class extends self.ITextInstance {},
	butonlar: class extends self.ISpriteInstance {}
}